# Generated by Django 2.0.3 on 2018-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180420_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model',
            field=models.CharField(default='iphone', max_length=20),
        ),
    ]
